config/routes.rb
Redit::Application.routes.draw do
  
  root "welcome#index"
  
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"
  
  resources :users, except: [:index] do 
    resources :stories
  end 


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :users
  belongs_to :stories
  
  validates :comments_message, presence: true
  validates :stories_id, presence: true
  validates :users_id, presence: true
end

app/models/story.rb
class Story < ActiveRecord::Base

  belongs_to :users
  has_many :users, through: :votes
  has_many :users, through: :comments

  validates :url, presence: true, uniqueness: true
  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :stories
  has_many :stories, through: :votes
  has_many :stories, through: :comments

  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_secure_password

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :users
  belongs_to :stories
  
  validates :vote_value, presence: true
  validates :stories_id, presence: true
  validates :users_id, presence: true
  validates :users_id, uniqueness: { scope: :stories_id } 

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new 
  end 

  def create 
    @user = User.find_by(email: params["email"])
    session[:user_id] = @user.id
    redirect_to root_path
  end 

  def destroy
  end 

end 

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def new
    @story = Story.new
    @user = User.find(session[:user_id])
  end 

  def create
    binding.pry
    @title = #TODO API CALL!!
    Story.new(url: params[:story][:url], title: @title)
  end 

  def show

  end 

private

  # def story_params
  #   params.require(:story).permit(:url)
  # end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render(:new)
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end


end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end 

end 

app/views/Welcome/index.html.erb
<h1>Redit</h1>

<div class="header">
  <%=link_to "Sign Up!", new_user_path %>
</div>


<div class="post_button">
  <%= button_to "+", new_user_story_path(session["user_id"]), method: "get" %>
</div>

app/views/session/new.html.erb
<%=form_tag "/session" do %>

  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Log in!" %>

<%end%>

app/views/stories/new.html.erb
<h1></h1>

<div class="story_form">
  <%=form_for  [@user, @story] do |f|%>
  <%=f.label :url %>
  <%=f.url_field :url %> 
  <%=f.submit "Submit" %>
  <%end%>
</div>

app/views/users/new.html.erb
<div class="sign_up">
  <h1>Sign Up</h1>

    <%= form_for @user do |f| %>
    <%= f.label :user_name %> 
    <%= f.text_field :user_name %> 

    <%= f.label :email %> 
    <%= f.text_field :email %> 

    <%= f.label :password %> 
    <%= f.password_field :password %> 
    <%= f.label :password_confirmation %> 
    <%= f.password_field :password_confirmation %> 

    <%= f.submit "Sign Up!" %>

  <%end%> 
</div>

app/views/users/show.html.erb
<div class="user_information" >
  <h2>Welcome <%=@user.user_name%></h2>
</div>